### ISSUE TITLE
VB Code

### ISSUE THREAD

**Issue by nameboxx** [thetrik/BitcoinVB#1]
Hi There.

In the VB6 bitcion example show the Bitcoin Bub key Address as Compressed. and WIF as Compressed too

Example :
Uncompressed private key to be imported (51 characters in base58, starts with 5) E.g.: 5HpneLQNKrcznVCQpzodYwAmZ4AoHeyjuRf9iAHAa498rP5kuWb
Compressed private key to be imported (52 characters in base58, starts with K or L) E.g.: KwFvTne98E1t3mTNAr8pKx67eUzFJWdSNPqPSfxMEtrueW7PcQzL

In JavaScript Examples 
uncompressed: 0x80 + [32-byte secret] + [4 bytes of Hash() of previous 33 bytes], base58 encoded
compressed: 0x80 + [32-byte secret] + 0x01 + [4 bytes of Hash() previous 34 bytes], base58 encoded

So How can I cover to uncompressed Public key Address And uncompressed Wif . in vb6 project

Thanks Regards
oncb17@yahoo.com

**Comment by nameboxx** [comment]
![p1](https://user-images.githubusercontent.com/50477532/106319120-00957f00-6282-11eb-809b-22635549afa5.JPG)

**Comment by thetrik** [comment]
The function secp256k1_ec_pubkey_serialize accepts the flags where you can specify which type of data you wish to extract (SECP256K1_EC_COMPRESSED/SECP256K1_EC_UNCOMPRESSED).

**Comment by nameboxx** [comment]
Thanks dude.
SECP256K1_EC_COMPRESSED  = 258
SECP256K1_EC_UNCOMPRESSED  = 2

I have managed the wifkey and pubkey Uncompressed.
Great work.thanks
![biGen](https://user-images.githubusercontent.com/50477532/106607647-9aa44280-6574-11eb-839f-c19ec8c0b13e.jpg)
